package com.wsvdmeer.pwncompanion.models

/**
 * Strategy - Actionable WiFi optimization strategy for Pwnagotchi.
 * Generated by AI based on learned patterns and current state.
 * M3 compliant with clear state representation.
 */
data class Strategy(
    val mode: StrategyMode,
    val recommendedChannels: List<Int>,     // Priority order
    val deauthMultiplier: Float,            // 0.0-2.0x adjustment
    val shouldCooldown: Boolean,            // Thermal management
    val sleepMode: Boolean,                 // Power management
    val reason: String,                     // Explanation for UI
    val confidence: Float,                  // 0.0-1.0 confidence level
    val timestamp: Long = System.currentTimeMillis()
)

/**
 * Strategy Mode - Determines Pwnagotchi behavior intensity.
 * Follows M3 state semantics.
 */
enum class StrategyMode {
    /**
     * Maximum aggression: High deauth rate, all channels scanned.
     * Use when: Client density high, battery/temp good, mood positive.
     */
    AGGRESSIVE,

    /**
     * Balanced approach: Moderate deauth, focused channels.
     * Use when: Normal conditions, mixed metrics.
     */
    BALANCED,

    /**
     * Conservative: Low deauth, passive scanning.
     * Use when: Low power, high temp, negative mood.
     */
    CONSERVATIVE,

    /**
     * Sleep mode: Minimal activity.
     * Use when: Battery critical, overheating, very tired.
     */
    SLEEP;

    /**
     * Get emoji representation for M3 UI.
     */
    fun getEmoji(): String = when (this) {
        AGGRESSIVE -> "🔥"
        BALANCED -> "⚖️"
        CONSERVATIVE -> "🔇"
        SLEEP -> "💤"
    }

    /**
     * Get M3 color indicator name.
     */
    fun getColorRole(): String = when (this) {
        AGGRESSIVE -> "error"        // Red/error color
        BALANCED -> "tertiary"       // Tertiary accent
        CONSERVATIVE -> "secondary"  // Secondary accent
        SLEEP -> "outline"           // Outline/muted
    }
}

